DELETE FROM MeterReadings WHERE UserId=1;

INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-02-01',14600.0,'Opening Feb',GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-02-05',14648.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-02-10',14700.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-02-15',14751.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-02-20',14801.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-02-25',14849.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-02-28',14880.0,'Closing Feb',GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-02-01',8100.0,'Opening Feb',GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-02-05',8122.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-02-10',8148.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-02-15',8173.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-02-20',8197.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-02-25',8220.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-02-28',8234.0,'Closing Feb',GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-03-01',14882.0,'Opening Mar',GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-03-05',14924.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-03-10',14970.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-03-15',15015.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-03-20',15058.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-03-25',15100.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-03-31',15148.0,'Closing Mar',GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-03-01',8236.0,'Opening Mar',GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-03-05',8254.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-03-10',8275.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-03-15',8294.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-03-20',8312.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-03-25',8329.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-03-31',8349.0,'Closing Mar',GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-04-01',15150.0,'Opening Apr',GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-04-05',15188.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-04-10',15228.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-04-15',15267.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-04-20',15305.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-04-25',15342.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-04-30',15378.0,'Closing Apr',GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-04-01',8351.0,'Opening Apr',GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-04-05',8366.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-04-10',8382.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-04-15',8397.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-04-20',8411.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-04-25',8424.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-04-30',8437.0,'Closing Apr',GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-05-01',15380.0,'Opening May',GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-05-05',15415.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-05-10',15452.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-05-15',15489.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Electricity','2026-05-19',15519.0,'Latest reading',GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-05-01',8439.0,'Opening May',GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-05-05',8450.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-05-10',8462.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-05-15',8473.0,NULL,GETUTCDATE(),GETUTCDATE());
INSERT INTO MeterReadings (UserId,FuelType,ReadingDate,ReadingValue,Notes,CreatedAt,UpdatedAt) VALUES (1,'Gas','2026-05-19',8481.0,'Latest reading',GETUTCDATE(),GETUTCDATE());

SELECT FuelType, YEAR(ReadingDate) as Yr, MONTH(ReadingDate) as Mo, COUNT(*) as Readings, MIN(ReadingValue) as OpenVal, MAX(ReadingValue) as CloseVal, MAX(ReadingValue)-MIN(ReadingValue) as Usage FROM MeterReadings WHERE UserId=1 GROUP BY FuelType, YEAR(ReadingDate), MONTH(ReadingDate) ORDER BY FuelType, Yr, Mo;
