name: Deploy API

on:
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Publish API
        run: dotnet publish FuelMeter.Api/FuelMeter.Api.csproj -c Release -o ./publish-api

      - name: Verify Published Files
        run: ls -la ./publish-api

      - name: Deploy API to Plesk
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.shrijiitservices.com
          username: fuelmeter_api
          password: Y1mz3Fe$WXff7B5K
          local-dir: ./publish-api/
          server-dir: /httpdocs/
