name: Build FuelMeter

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install MAUI Workloads
        run: dotnet workload install maui android maui-android

      - name: Restore Workloads
        run: dotnet workload restore FuelMeter.csproj

      - name: Restore NuGet Packages
        run: dotnet restore FuelMeter.csproj

      - name: Build
        run: dotnet build FuelMeter.csproj --configuration Release --no-restore
