name: Deploy Website

on:
  workflow_dispatch:

jobs:
  deploy-website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Publish Website
        run: dotnet publish FuelMeter.Web/FuelMeter.Web.csproj -c Release -o ./publish-website

      - name: Verify Published Files
        run: ls -la ./publish-website

      - name: Deploy Website to Plesk
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.shrijiitservices.com
          username: fuelmeter_website
          password: Y1mz3Fe$WXff7B5K
          local-dir: ./publish-website/
          server-dir: /
